".oh-my-zsh":
  type: "archive"
  url: "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".oh-my-zsh/custom/themes/powerlevel10k":
  type: "archive"
  url: "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

{{- if .iswork }}
".oh-my-zsh/custom/plugins/zsh-aws-vault":
  type: "archive"
  url: "https://github.com/blimmer/zsh-aws-vault/archive/refs/heads/main.zip"
  exact: true
  refreshPeriod: "168h"
{{- end }}

{{ range list "CascadiaCode" "CascadiaCodeItalic" "CascadiaCodePL" "CascadiaCodePLItalic" }}
"Library/Fonts/{{ . }}.ttf":
  type: "file"
  url: "https://github.com/microsoft/cascadia-code/releases/download/v2111.01/CascadiaCode-2111.01.zip"
  filter:
    command: tar
    args:
        - -xf
        - "-"
        - --strip-components=1
        - --to-stdout
        - ttf/{{ . }}.ttf
{{ end }}
